In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [5]:
PATH  = '/home/konradkaranowski/personalized-nlp/storage'

In [38]:
df = pd.read_csv(os.path.join('/home/konradkaranowski/storage/personalized-nlp/personalized_nlp/storage/clarin_emo_sent/annotations.tsv'), sep='\t')

In [39]:
dim_columns = [df.columns]
df['uid'] = df['text_id'].astype(str) + ' ' + df['user_id'].astype(str)

In [41]:
z = df.groupby('uid').mean()[dim_columns].round().astype(int)
for k in dim_columns:
    print(df[k].unique())

[0 1]
[0 1]
[0 1]
[0 1]
[0 1]
[1 0]
[0 1]
[0 1]
[0 1]
[1 0]
[0 1]

In [42]:
z

,radość,zaufanie,przeczuwanie,zdziwienie,strach,smutek,wstręt,gniew,pozytywny,negatywny,neutralny
uid,,,,,,,,,,,
0 0,0,0,0,0,0,1,0,0,0,1,0
0 1,0,0,0,0,0,0,0,1,0,1,0
0 3,0,0,0,0,0,0,1,0,0,1,0
0 4,0,0,0,0,0,0,0,1,0,1,0
0 5,0,0,0,1,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
999 2,1,0,0,1,0,0,0,0,1,0,0
999 3,1,0,1,1,1,0,0,0,1,1,0
999 4,1,0,1,1,1,0,0,0,1,0,0
999 5,1,0,0,0,1,0,0,0,1,1,0
999 6,1,1,1,0,1,1,0,0,1,1,0

In [11]:
for user in pd.unique(df['user_id']):
    df_uo = df[df['user_id'] == user]
    df_uo.to_csv(f'/home/konradkaranowski/personalized-nlp/personalized_nlp/storage/clarin_emo_text/annotations_user={user}.tsv', index=False, sep='\t')