In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:
PATH  = '/home/konradkaranowski/personalized-nlp/storage'

In [4]:
df = pd.read_csv(os.path.join('/home/konradkaranowski/personalized-nlp/personalized_nlp/storage/clarin_emo_text/annotations.tsv'), sep='\t')

In [5]:
print(f'Num of annotations: {len(df)}')
df.groupby('user_id').count()

Num of annotations: 6286

,text_id,radość,zaufanie,przeczuwanie,zdziwienie,strach,smutek,wstręt,gniew,pozytywny,negatywny,neutralny
user_id,,,,,,,,,,,,
0,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097,1097
1,998,998,998,998,998,998,998,998,998,998,998,998
2,1008,1008,1008,1008,1008,1008,1008,1008,1008,1008,1008,1008
3,507,507,507,507,507,507,507,507,507,507,507,507
4,769,769,769,769,769,769,769,769,769,769,769,769
5,865,865,865,865,865,865,865,865,865,865,865,865
6,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042,1042

In [11]:
for user in pd.unique(df['user_id']):
    df_uo = df[df['user_id'] == user]
    df_uo.to_csv(f'/home/konradkaranowski/personalized-nlp/personalized_nlp/storage/clarin_emo_text/annotations_user={user}.tsv', index=False, sep='\t')