In [1]:
import os

import pandas as pd

In [2]:
data_dir = os.path.join('..', 'storage', 'data', 'mhs', 'data_raw')

dev_df = pd.read_csv(os.path.join(data_dir, 'dev.tsv'), sep='\t')
test_df = pd.read_csv(os.path.join(data_dir, 'test.tsv'), sep='\t')
train_df = pd.read_csv(os.path.join(data_dir, 'train.tsv'), sep='\t')

dev_df['split'] = 'val'
test_df['split'] = 'test'
train_df['split'] = 'train'

In [3]:
for ind, df in enumerate([dev_df, test_df, train_df]):

    if ind == 0:
        full_df = df

    else:
        full_df = pd.concat([full_df, df])

full_df = full_df.rename(columns = {'username': 'annotator'})

In [4]:
def set_id(df, column_name) -> pd.DataFrame:
    values_list = df[column_name].unique().tolist()

    df[f'{column_name}_id'] = df[column_name].apply(lambda x: values_list.index(x))
    
    return df

In [5]:
full_df = set_id(full_df, 'text')

full_df = set_id(full_df, 'annotator')

In [6]:
full_df

,index,annotator,sentiment,respect,insult,humiliate,dehumanize,violence,genocide,hatespeech,text,split,text_id,annotator_id
0,20,1329,4,4,3,4,4,0,0,2,Lmao trash ass commies. aMeRiCaNS fAT AmURIcAn...,val,0,0
1,21,1329,2,1,0,0,0,0,0,0,happy pride month i'm gay URL,val,1,0
2,22,1329,3,3,3,3,2,2,0,0,That Dick Succ,val,2,0
3,23,1329,4,4,4,3,4,4,3,2,Hitler didn't finish it. Can u. If a nigger ur...,val,3,0
4,24,1329,3,3,3,3,3,1,0,2,"girl it's CA, we all know lisa is a good perso...",val,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29165,129165,3985,2,2,1,1,2,0,0,0,Her pussy cant stop dripping cream with that b...,train,8300,2315
29166,129166,3985,3,2,2,1,2,1,0,0,"No, the chances of a muslim shooting you in Am...",train,1519,2315
29167,129167,3985,4,4,3,3,3,2,0,2,Being a woman had fuck all go do with her fail...,train,2100,2315
29168,129168,3985,4,4,4,3,4,1,1,2,There are not any jew signatures on our Declar...,train,915,2315
29169,129169,3985,2,2,1,1,1,1,0,0,The #POHA launch conference starts tomorrow an...,train,16529,2315

In [10]:
for dimension in ['sentiment', 'insult', 'humiliate', 'violence', 'hatespeech']:
    for dataset_type in ['train', 'val', 'test']:
        print(f'value count for {dimension} {dataset_type}:', 
              f'{full_df[full_df["split"] == dataset_type][dimension].value_counts()}', 
              sep='\n')

value count for sentiment train:
4    14143
3     7878
2     4161
1     1736
0     1252
Name: sentiment, dtype: int64
value count for sentiment val:
4    2997
3    2447
0    1646
2    1515
1    1212
Name: sentiment, dtype: int64
value count for sentiment test:
4    5060
3    2951
2    1598
1     717
0     562
Name: sentiment, dtype: int64
value count for insult train:
4    10217
3     8886
2     4003
1     3245
0     2819
Name: insult, dtype: int64
value count for insult val:
3    2690
0    2348
4    2010
1    1393
2    1376
Name: insult, dtype: int64
value count for insult test:
4    3588
3    3497
2    1568
1    1130
0    1105
Name: insult, dtype: int64
value count for humiliate train:
3    9134
4    7312
2    5185
1    4190
0    3349
Name: humiliate, dtype: int64
value count for humiliate val:
0    2522
3    2474
1    1743
2    1662
4    1416
Name: humiliate, dtype: int64
value count for humiliate test:
3    3454
4    2602
2    1978
1    1530
0    1324
Name: humiliate, dtype: int64
value count for violence train:
0    13543
1     7236
4     2986
2     2744
3     2661
Name: violence, dtype: int64
value count for violence val:
0    5886
1    2234
2     775
3     546
4     376
Name: violence, dtype: int64
value count for violence test:
0    5025
1    2636
4    1162
3    1052
2    1013
Name: violence, dtype: int64
value count for hatespeech train:
0    16228
2    10928
1     2014
Name: hatespeech, dtype: int64
value count for hatespeech val:
0    6956
2    2185
1     676
Name: hatespeech, dtype: int64
value count for hatespeech test:
0    6140
2    3904
1     844
Name: hatespeech, dtype: int64

In [31]:
save_dir = os.path.join('..', 'storage', 'data', 'mhs')

data_columns = ['text_id', 'text']
annotations_columns = ['text_id', 'annotator_id', 'sentiment', 'respect', 'insult', 'humiliate', 
                       'dehumanize', 'violence', 'genocide', 'hatespeech','split']

full_df[data_columns].to_csv(os.path.join(save_dir, 'data.csv'), index=False)
full_df[annotations_columns].to_csv(os.path.join(save_dir, 'annotations.csv'), index=False)